version: '3.4'

services:
  optimal.api:
    image: ${DOCKER_REGISTRY-}optimalapi
    build:
      context: .
      dockerfile: Optimal.API/Dockerfile
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
