version: '3.4'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
  
  workspacedb:
    image: mongo

  optimal.api:
    image: ${DOCKER_REGISTRY-}optimalapi
    build:
      context: .
      dockerfile: Optimal.API/Dockerfile

  artificialintel.api:
    image: ${DOCKER_REGISTRY-}artificialintelapi
    build:
      context: .
      dockerfile: ArtificialIntel.API/Dockerfile
  
volumes:
  mongo_data:

