version: '3.4'

services:
  
  rabbitmq:
    image: rabbitmq:3-management-alpine
  
  redisdb:
    image: redis:latest

  workspacedb:
    image: mongo

  react-app:
     image: vpp090/optimizee.fe:v1
     
  optimal.api:
    image: vpp090/optimal.api:v1
    

  artificialintel.api:
    image: vpp090/ai.api:v1
  
  portainer:
     image: portainer/portainer-ce

volumes:
  mongo_data:
  redis_data:
  portainer_data:

